Updates and scripts for fonts and themes

diff --git a/.chezmoiscripts/run_onchange_after_01-brew-installs.sh.tmpl b/.chezmoiscripts/run_onchange_after_01-brew-installs.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_01-brew-installs.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_01-brew-installs.sh.tmpl
@@ -29,6 +29,31 @@ echo
 _print_prog homebrew "updating..."
 brew update
 
+# Remove old fonts
+brew uninstall -f --zap font-meslo-lgs-nf font-monaco-for-powerline
+
+# Remove non-homebrew vscode
+if [ -d "/Applications/Visual Studio Code.app" ]; then
+  if ! brew ls --cask visual-studio-code --versions &> /dev/null; then
+    echo
+    _print_info "Removing non-homebrew vscode app"
+    osascript -e 'quit app "Visual Studio Code"'
+    sudo -p "OSX password for %p:" rm -rf "/Applications/Visual Studio Code.app"
+    if [ $? -ne 0 ]; then
+      _print_error "Could not remove 'Visual Studio Code' app."
+      _print_info "Try removing manually or run this script again."
+      echo
+      exit 1
+    fi
+  fi
+fi
+
+if [ -L "/usr/local/bin/code" ]; then
+  echo
+  _print_info "Removing non-homebrew VSCode symlink"
+  sudo -p "OSX password for %p:" rm -f "/usr/local/bin/code"
+fi
+
 echo
 _print_prog homebrew "bundling..."
 brew bundle --file="$HOME/Brewfile"
@@ -36,6 +61,7 @@ brew bundle --file="$HOME/Brewfile"
 echo
 _print_prog homebrew "removing unused dependencies..."
 brew autoremove
+# brew cleanup
 
 echo
 keep_in_dock "Figma"
